class ArrayConstants {
  Map<int, List<String>> getZodiacHour() {
    var canChiGio = {
      0: [
        "Giáp Tý",
        "Ất Sửu",
        "Bính Dần",
        "Đinh Mão",
        "Mậu Thìn",
        "Kỷ Tị",
        "Canh Ngọ",
        "Tân Mùi",
        "Nhâm Thân",
        "Quý Dậu",
        "Giáp Tuất",
        "Ất Hợi"
      ],
      5: [
        "Giáp Tý",
        "Ất Sửu",
        "Bính Dần",
        "Đinh Mão",
        "Mậu Thìn",
        "Kỷ Tị",
        "Canh Ngọ",
        "Tân Mùi",
        "Nhâm Thân",
        "Quý Dậu",
        "Giáp Tuất",
        "Ất Hợi"
      ],
      1: [
        "Bính Tý",
        "Đinh Sửu",
        "Mậu Dần",
        "Kỷ Mão",
        "Canh Thìn",
        "Tân Tị",
        "Nhâm Ngọ",
        "Quý Mùi",
        "Giáp Thân",
        "Ất Dậu",
        "Bính Tuất",
        "Đinh Hợi"
      ],
      6: [
        "Bính Tý",
        "Đinh Sửu",
        "Mậu Dần",
        "Kỷ Mão",
        "Canh Thìn",
        "Tân Tị",
        "Nhâm Ngọ",
        "Quý Mùi",
        "Giáp Thân",
        "Ất Dậu",
        "Bính Tuất",
        "Đinh Hợi"
      ],
      2: [
        "Mậu Tý",
        "Kỷ Sửu",
        "Canh Dần",
        "Tân Mão",
        "Nhâm Thìn",
        "Quý Tị",
        "Giáp Ngọ",
        "Ất Mùi",
        "Bính Thân",
        "Đinh Dậu",
        "Mậu Tuất",
        "Kỷ Hợi"
      ],
      7: [
        "Mậu Tý",
        "Kỷ Sửu",
        "Canh Dần",
        "Tân Mão",
        "Nhâm Thìn",
        "Quý Tị",
        "Giáp Ngọ",
        "Ất Mùi",
        "Bính Thân",
        "Đinh Dậu",
        "Mậu Tuất",
        "Kỷ Hợi"
      ],
      3: [
        "Canh Tý",
        "Tân Sửu",
        "Nhâm Dần",
        "Quý Mão",
        "Giáp Thìn",
        "Ất Tị",
        "Bính Ngọ",
        "Đinh Mùi",
        "Mậu Thân",
        "Kỷ Dậu",
        "Canh Tuất",
        "Tân Hợi"
      ],
      8: [
        "Canh Tý",
        "Tân Sửu",
        "Nhâm Dần",
        "Quý Mão",
        "Giáp Thìn",
        "Ất Tị",
        "Bính Ngọ",
        "Đinh Mùi",
        "Mậu Thân",
        "Kỷ Dậu",
        "Canh Tuất",
        "Tân Hợi"
      ],
      4: [
        "Nhâm Tý",
        "Quý Sửu",
        "Giáp Dần",
        "Ất Mão",
        "Bính Thìn",
        "Đinh Tị",
        "Mậu Ngọ",
        "Kỷ Mùi",
        "Canh Thân",
        "Tân Dậu",
        "Nhâm Tuất",
        "Quý Hợi"
      ],
      9: [
        "Nhâm Tý",
        "Quý Sửu",
        "Giáp Dần",
        "Ất Mão",
        "Bính Thìn",
        "Đinh Tị",
        "Mậu Ngọ",
        "Kỷ Mùi",
        "Canh Thân",
        "Tân Dậu",
        "Nhâm Tuất",
        "Quý Hợi"
      ],
    };
    return canChiGio;
  }
}
